### ISSUE TITLE
Injection Crash

### ISSUE THREAD

**Issue by Dufiw** [maecry/asphyxia#3]
**Describe the bug**
When trying to inject (manual map) the cmd prompt does its thing then crashes
**To Reproduce**
Just try to inject when the current GitHub version

**Expected behavior**
Unhandled exception at 0x0000000000000000 in cs2.exe: 0xC0000005: Access violation executing location 0x0000000000000000.

I'm sure you are aware of this.

**Comment by maecry** [comment]
Use loadlibrary
